export const productInfo = [
  {
    imageLink: "/product-list-1.jpg",
    footerTitle: "Graphic Design",
    footerDescription: "English Department",
    originalPrice: "$16.48",
    discountedPrice: "$6.48",
    footerImg: "./product-colors.svg",
  },
  {
    imageLink: "/product-list-1.jpg",
    footerTitle: "Graphic Design",
    footerDescription: "English Department",
    originalPrice: "$16.48",
    discountedPrice: "$6.48",
    footerImg: "./product-colors.svg",
  },
  {
    imageLink: "/product-list-1.jpg",
    footerTitle: "Graphic Design",
    footerDescription: "English Department",
    originalPrice: "$16.48",
    discountedPrice: "$6.48",
    footerImg: "./product-colors.svg",
  },
  {
    imageLink: "/product-list-1.jpg",
    footerTitle: "Graphic Design",
    footerDescription: "English Department",
    originalPrice: "$16.48",
    discountedPrice: "$6.48",
    footerImg: "./product-colors.svg",
  },
  {
    imageLink: "/product-list-1.jpg",
    footerTitle: "Graphic Design",
    footerDescription: "English Department",
    originalPrice: "$16.48",
    discountedPrice: "$6.48",
    footerImg: "./product-colors.svg",
  },
  {
    imageLink: "/product-list-1.jpg",
    footerTitle: "Graphic Design",
    footerDescription: "English Department",
    originalPrice: "$16.48",
    discountedPrice: "$6.48",
    footerImg: "./product-colors.svg",
  },
  {
    imageLink: "/product-list-1.jpg",
    footerTitle: "Graphic Design",
    footerDescription: "English Department",
    originalPrice: "$16.48",
    discountedPrice: "$6.48",
    footerImg: "./product-colors.svg",
  },
  {
    imageLink: "/product-list-1.jpg",
    footerTitle: "Graphic Design",
    footerDescription: "English Department",
    originalPrice: "$16.48",
    discountedPrice: "$6.48",
    footerImg: "./product-colors.svg",
  },
];
